/**
 * @module open-api.utils
 * @description Provides utilities for interacting with the `better-auth` OpenAPI plugin.
 * These functions are designed using the Effect-TS functional programming paradigm.
 */

// AI-GENERATED FILE - DO NOT EDIT

// @ai-prompt
// Implement a utility function `getOpenApiSpecification` using Effect-TS.
// 1.  The function should not accept any arguments.
// 2.  It should make a request to the endpoint exposed by the `better-auth` OpenAPI plugin (e.g., `/api/auth/openapi.json`).
// 3.  This is an effectful operation (network request).
// 4.  The `Effect` should succeed with the OpenAPI specification object.
// 5.  It should fail with a `NetworkError` or `ApiError`.
// 6.  Follow the JSDoc template for effectful functions.
/**
 * Fetches the OpenAPI specification from the `better-auth` server.
 *
 * @description This function performs a network request to retrieve the OpenAPI JSON specification
 * generated by the `better-auth` OpenAPI plugin. The operation is wrapped in an `Effect`.
 *
 * @returns {Effect.Effect<OpenApiSpec, NetworkError | ApiError, HttpClient>} An `Effect` that resolves with the
 * OpenAPI specification object or fails with a network or API error. Requires an `HttpClient` in its context.
 */
export const getOpenApiSpecification = () => {
  // AI, implement the function here.
};
