version: "3.9"

services:
  postgres:
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Must be set in production
    ports:
      - "127.0.0.1:5432:5432" # Bind to localhost only
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data # Production mount
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3

  # Remove pgAdmin in production
  pgadmin:
    profiles:
      - dev-only
