# =================================================================================================
# Docker Compose Production Override
# =================================================================================================
#
# This file provides production-specific overrides for the NGINX infrastructure.
# Use it in combination with the base docker-compose.yaml file.
#
# Usage:
#   docker compose -f tools/nginx/docker-compose.yaml -f tools/nginx/docker-compose.prod.yaml up -d
#
# =================================================================================================

version: "3.8"

services:
  # Edge Proxy - Production Configuration
  proxy-edge:
    environment:
      - NGINX_ENV=production

    # Production port mapping (ensure 443 is available)
    ports:
      - "80:80"
      - "443:443"

    # Production volumes
    volumes:
      - ./secrets/tls:/etc/nginx/tls:ro
      # Production custom pages
      - ./proxy-edge/html:/usr/share/nginx/html:ro

    # Stricter resource limits for production
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M

      # Restart policy for production
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    # Production logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend Load Balancer - Production Configuration
  lb-frontend:
    environment:
      - NGINX_ENV=production

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # API Load Balancer - Production Configuration
  lb-api:
    environment:
      - NGINX_ENV=production

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Email Load Balancer - Production Configuration
  lb-email:
    environment:
      - NGINX_ENV=production

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Production-specific network configuration
networks:
  nginx-internal:
    driver: bridge

  app-network:
    driver: bridge
